// <auto-generated />
using System;
using BluesoftBank.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BluesoftBank.Infrastructure.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20260416162614_RemoveTransaccionCiudadOwnedEntity")]
    partial class RemoveTransaccionCiudadOwnedEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BluesoftBank.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Discriminador")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);

                    b.HasDiscriminator<string>("Discriminador").HasValue("Cliente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BluesoftBank.Domain.Entities.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminador")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NumeroCuenta")
                        .IsUnique();

                    b.ToTable("Cuentas", (string)null);

                    b.HasDiscriminator<string>("Discriminador").HasValue("Cuenta");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BluesoftBank.Domain.Entities.Transaccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CiudadNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsFueraDeCiudadOrigen")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2(7)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoResultante")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId", "Fecha");

                    b.HasIndex("EsFueraDeCiudadOrigen", "Fecha");

                    b.ToTable("Transacciones", (string)null);
                });

            modelBuilder.Entity("BluesoftBank.Domain.Entities.Empresa", b =>
                {
                    b.HasBaseType("BluesoftBank.Domain.Entities.Cliente");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Nit");

                    b.HasIndex("Nit")
                        .IsUnique()
                        .HasFilter("[Nit] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Empresa");
                });

            modelBuilder.Entity("BluesoftBank.Domain.Entities.PersonaNatural", b =>
                {
                    b.HasBaseType("BluesoftBank.Domain.Entities.Cliente");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Cedula");

                    b.HasIndex("Cedula")
                        .IsUnique()
                        .HasFilter("[Cedula] IS NOT NULL");

                    b.HasDiscriminator().HasValue("PersonaNatural");
                });

            modelBuilder.Entity("BluesoftBank.Domain.Entities.CuentaAhorro", b =>
                {
                    b.HasBaseType("BluesoftBank.Domain.Entities.Cuenta");

                    b.HasDiscriminator().HasValue("CuentaAhorro");
                });

            modelBuilder.Entity("BluesoftBank.Domain.Entities.CuentaCorriente", b =>
                {
                    b.HasBaseType("BluesoftBank.Domain.Entities.Cuenta");

                    b.Property<decimal>("CupoSobregiro")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CupoSobregiro");

                    b.HasDiscriminator().HasValue("CuentaCorriente");
                });

            modelBuilder.Entity("BluesoftBank.Domain.Entities.Cliente", b =>
                {
                    b.OwnsOne("BluesoftBank.Domain.ValueObjects.Ciudad", "Ciudad", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CiudadNombre");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Ciudad")
                        .IsRequired();
                });

            modelBuilder.Entity("BluesoftBank.Domain.Entities.Cuenta", b =>
                {
                    b.OwnsOne("BluesoftBank.Domain.ValueObjects.Ciudad", "Ciudad", b1 =>
                        {
                            b1.Property<Guid>("CuentaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CiudadNombre");

                            b1.HasKey("CuentaId");

                            b1.ToTable("Cuentas");

                            b1.WithOwner()
                                .HasForeignKey("CuentaId");
                        });

                    b.Navigation("Ciudad")
                        .IsRequired();
                });

            modelBuilder.Entity("BluesoftBank.Domain.Entities.Transaccion", b =>
                {
                    b.HasOne("BluesoftBank.Domain.Entities.Cuenta", null)
                        .WithMany("Transacciones")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BluesoftBank.Domain.Entities.Cuenta", b =>
                {
                    b.Navigation("Transacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
